GET http://localhost:3000/account/

###

GET http://localhost:3000/account/login
Content-Type: application/json

{
    "email": "fane@fanesrl.com",
    "password": "1234"
}

###

GET http://localhost:3000/account/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgzNzExNDNjLTVlZmEtNGRhMy04MmFiLTg0ZDIyYzcwMWUzYiIsImZpcnN0X25hbWUiOiJGYW5lIiwibGFzdF9uYW1lIjoiVmFuY2ljYSIsImVtYWlsIjoiZmFuZUBmYW5lc3JsLmNvbSIsInBob25lX251bWJlciI6IjA3NDYzNTU1NTUiLCJpYXQiOjE3MjEzODIzMzIsImV4cCI6MTcyMTQ2ODczMn0.Sn92U996-_7kc9QRueH_MnnLFimx5Ift_v7S1YY-TFk

###

GET http://localhost:3000/account/test

###

PUT http://localhost:3000/account/modify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgzNzExNDNjLTVlZmEtNGRhMy04MmFiLTg0ZDIyYzcwMWUzYiIsImZpcnN0X25hbWUiOiJGYW5lIiwibGFzdF9uYW1lIjoiU3BvaXRvcnVsIiwiZW1haWwiOiJmYW5lQGdtYWlsLmNvbSIsInBob25lX251bWJlciI6IjA3NDYzNTU1NTUiLCJpYXQiOjE3MjEzNzg5NTEsImV4cCI6MTcyMTQ2NTM1MX0.2auEmdWYD663c2hKc56BfRuKyjvus4e-ksCn0NCcfgE
Content-Type: application/json

{
    "first_name": "Fane",
    "last_name": "Vancica",
    "email": "fane@fanesrl.com",
    "phone_number": "0746355555"
}

###

POST http://localhost:3000/account/create
Content-Type: application/json

{
    "first_name": "Alunelu",
    "last_name": "Gogoasa",
    "email": "aluna@gmail.com",
    "password": "bobita",
    "phone_number": "0765467391"
}

###

GET http://localhost:3000/account/login
Content-Type: application/json

{
    "email": "gogo@gmail.com",
    "password": "bobita"
}

###

PUT http://localhost:3000/account/modify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjZDNmN2IxLTQyZmUtNDhjYS04NjVhLTRiNTI0NDA1NDg5YyIsImZpcnN0X25hbWUiOiJBbHVuZWx1IiwibGFzdF9uYW1lIjoiR29nb2FzYSIsImVtYWlsIjoiYWx1bmFAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiMDc2NTQ2NzM5MSIsImlhdCI6MTcyMTM4Mjc5MiwiZXhwIjoxNzIxNDY5MTkyfQ.ZHHZTNc9_s3HXFK-ZKRx2vtklWfAcfaaUoJ8EB0kiBs
Content-Type: application/json

{
    "email": "gogo@gmail.com"
}

###

DELETE http://localhost:3000/account/delete
Authorization: Bearer eyJhGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjZDNmN2IxLTQyZmUtNDhjYS04NjVhLTRiNTI0NDA1NDg5YyIsImZpcnN0X25hbWUiOiJBbHVuZWx1IiwibGFzdF9uYW1lIjoiR29nb2FzYSIsImVtYWlsIjoiYWx1bmFAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiMDc2NTQ2NzM5MSIsImlhdCI6MTcyMTM4Mjc5MiwiZXhwIjoxNzIxNDY5MTkyfQ.ZHHZTNc9_s3HXFK-ZKRx2vtklWfAcfaaUoJ8EB0kiBs
